### ISSUE TITLE
Please comply with the license of Async

### ISSUE THREAD

**Issue by duemunk** [khoiln/RunKit#5]
Hi

Please comply to the license of [Async](https://github.com/duemunk/Async) by including `Copyright (c) 2014 Tobias Due Munk`.

It's license states:
```
The MIT License (MIT)
Copyright (c) 2014 Tobias Due Munk
Permission is hereby granted, [...]
The above copyright notice and this permission notice shall be included in all copies 
or substantial portions of the Software
```

RunKit is arguably a copy of Async in the very least it contains `substantial portions of` it.

**Comment by khoiln** [comment]
Sorry if I have upset you in any case. I've updated the License and also Readme. Please tell me if I can do anything else :)

**Comment by duemunk** [comment]
Thanks for getting back to me.
I have some follow up questions:

1. You state the reason for creating this project was to avoid using the Async keyword. Why not just make your own `.podspec` file with another module name and point directly to the Async GitHub repo?
2. Why didn't just fork the existing project?
3. Why didn't respond to previous issues on this matter by explaining your motive instead of just closing issues?
4.  Why have you pushed it to the CocoaPods trunk if it's for internal use only?
